### ISSUE TITLE
Request for Permission to Use Your Work in an Article

### ISSUE THREAD

**Issue by mbaneshi** [tonkeeper/w5#8]
Dear Tonkeeper developers,

I trust this message finds you well. I'm Mehdi Baneshi, currently working on an article titled "Managing Gas in a Contract" for the TON community. The article aims to assist Func developers in writing more efficient code.

During my research, I came across the recent update in your project, specifically the transition from wallet version 4 to version 5. I find this update exceptionally valuable, especially considering the reduction in size and gas fees. I believe it would significantly enhance the quality and depth of my article.

Before proceeding, I would like to request your permission to include excerpts or references to this version update in my article. I am dedicated to providing clear attribution and ensuring that my use aligns with your intentions.

Thank you for considering my request. I eagerly await your response.

Best regards,

Mehdi Baneshi

[Article Discussion page](https://github.com/ton-society/grants-and-bounties/issues/20)

**Comment by siandreev** [comment]
Hi, sure, you can use it

**Comment by mbaneshi** [comment]
Thank you
